var errors = {
    invalid_parameters: [100, 'Invalid Parameters'],
    server_error: [200, 'Failed to process the request.'],
    data_already_exist_error: [201, 'Data already exist'],
    otp_error: [300, 'OTP submitted is invalid.'],
    pwd_error: [310, 'Password submitted is incorrect.'],
    pwd_not_setup_error: [315, 'Login via Password Setup incomplete.'],
    pwd_max_atmpt_error: [320, 'You have entered wrong password too many times.'],
    weak_pwd_error: [330, 'Password Submitted is too weak.'],
    profile_not_found: [400, 'Profile was not found.'],
    custom_error: [420, ''],
    phone_number_not_found: [500, 'Phone number was not found.'],
    profile_already_exists: [600, 'Profile already exists.'],
    account_not_verified: [700, 'Account not verified yet.'],
    account_email_save_error: [710, 'Account Email Could not be Saved.'],
    invalid_group_code: [800, 'Invalide Group Code.'],
    no_group_found: [900, 'No Group Found'],
    no_group_member_found: [910, 'No Group Member Found'],
    profile_type_not_teacher: [
      1000,
      'Action permitted only for profile type Teacher.',
    ],
    used_group_code: [1100, 'Group Code already in use.'],
    authentication_error: [1200, 'Authentication Error.'],
    group_already_exists: [1300, 'Group Already Exists.'],
    not_a_member: [1400, 'Profile must be a member of the group.'],
    already_administrator: [1500, 'Profile is already an Administrator.'],
    already_member: [1600, 'Profile is already a Member.'],
    already_banned: [1700, 'Profile is already Banned.'],
    cannot_ban_administrator: [1800, 'Cannot ban Administrator.'],
    not_banned: [1900, 'Profile is not Banned.'],
    group_already_two_way: [2000, 'Group is already two way.'],
    group_already_one_way: [2100, 'Group is already one way.'],
    no_messages_found: [2200, 'Messages were not found for this conversation.'],
    no_server_response: [2300, 'No response from server.'],
    lower_mobile_app_version: [
      2400,
      'Mobile App Version is lower than last login version',
    ],
    profile_groups_exist: [
      2500,
      'Leave all joined groups with this profile before deleting profile',
    ],
    group_one_way: [2600, 'Group is One Way Only'],
    only_one_profile: [2700, 'User currently has only one profile active'],
    group_single_admin: [2800, 'Group has only one admin active at the moment'],
    group_admin_cannot_leave: [2900, 'Group Admin cannot leave the group'],
    banned_group_member: [3000, 'User is banned in the group'],
    group_admin: [3100, 'User is a Group Admin'],
    multiple_group_admins: [3200, 'Multiple group admins present in group'],
    group_message_not_allowed: [
      3300,
      'User is not allowed to perform group message activity',
    ],
    no_account_found: [3400, 'Account does not exist'],
    otp_expired: [3500, 'OTP has expired'],
    mid_not_found: [3600, 'Message id not found'],
    device_tokn_already_exists: [3700, 'Device Token already exists on server'],
    msg_ttyp_not_group: [3800, 'Message recipient type not group'],
    msg_type_not_valid: [3900, 'Message type is not group message'],
    not_a_group_admin: [4000, 'Not a group admin'],
    token_auth_failure: [4100, 'Failed to authenticate token'],
    token_not_found: [4200, 'Access without token is not authorised'],
    no_refresh_token: [4300, 'Refresh token not allowed'],
    invalid_secret_key: [4400, 'Secret Key Invalid'],
    token_already_issued: [4500, 'Refresh Token already issued'],
    rf_token_not_gen: [4600, 'Refresh token generation error'],
    invalid_refresh_token: [4700, 'Refresh Token is invalid'],
    refresh_token_expired: [4800, 'Refresh token expired'],
    no_msg_found: [4900, 'Message not found'],
    refresh_token_denied: [5000, 'Refresh token access denied'],
    access_token_denied: [5100, 'Access Token Denied'],
    route_not_found: [5200, 'Route not found'],
    media_in_processing: [5300, 'Media In Processing'],
    invalid_account_data: [5400, 'Invalid Account Data'],
    not_authorized: [5500, 'not authorized'],
    invalid_AT: [5600, 'Invalid At'],
    account_not_found: [5700, 'Account Not Found'],
    cannot_ban_your_own_profile: [5800, 'Cannot ban your own profile'],
    already_acknowledged: [5900, 'Already Acknowledged'],
    forbidden: [6000, 'Forbidden'],
    too_many_requests: [6100, 'Too many requests. Please try again later'],
    signup_call_rejected: [6200, 'Please try again later'],
    banned_for_call_me: [6300, 'Please try again later'],
    call_otp_expired: [6400, 'Your otp has expired. Please request a new otp'],
    call_max_atmpt_reached: [
      6500,
      'You have reached max limit. Please try after sometime',
    ],
    group_not_active: [6600, 'Group Not Active'],
    alive_groupmembers_present: [6700, 'Group Still has Alive Members'],
    groupmessage_not_allowed: [6800, 'Groupmessage_Not_Allowed'],
    message_length_small: [9000, 'Message_Length_Small'],
    profile_name_missing: [9100, 'Profile_Name_Missing'],
    profile_not_groupmember: [9200, 'Profile_Is_Not_GroupMember'],
    profile_not_group_admin: [9300, 'Profile_Is_Not_Group_Admin'],
    group_is_inactive: [9400, 'Group_Is_Not_Active'],
    image_filename_invalid: [9500, 'Image_Filename_Invalid'],
    wrong_image_dimensions: [9600, 'Image_Dimension_Wrong'],
    thumb_file_size_exceeded: [9650, 'thumb_file_size_exceeded'],
    invalid_thumb_file_type: [9650, 'invalid_thumb_file_type'],
    only_jpg_type_image_allowed: [9700, 'Only_Jpg_Type_Image_Allowed'],
    were_not_groupmember: [9800, 'You Were Not a Groupmember'],
    not_authorised: [9900, 'You are Not Authorised For This Request'],
    plugin_package_free: [10000, 'Plugin Is Free In This Group'],
    user_already_subscribed: [11000, 'Already Subscribed For This Package'],
    user_not_subscribed: [12000, 'User Is Not Subscribed To Plugin Package'],
    coupon_code_expired: [13000, 'Coupon Code Has Expired'],
    payment_trxn_skip: [14000, 'Payment Transaction Not Required'],
    parameter_not_found: [15000, 'Access without Parameters is not authorised'],
    user_subscription_required: [
      12500,
      'You need to subscribe to enable your access.',
    ],
    user_subscription_ended: [
      12990,
      'Oops, your subscription has expired. Kindly renew your subscription.',
    ],
    group_not_paid: [16000, 'Group is not paid'],
    group_packages_not_found: [17000, 'Group packages not found'],
    group_plugin_type_not_group_join: [
      18000,
      'Group plugin is not of type GROUP_JOIN',
    ],
    Group_Package_Price_Mismatch: [18500, 'Group Package Price Mismatch'],
    plugin_already_active_in_group: [
      19000,
      'Plugin is already Active in the group',
    ],
    plugin_already_deactive_in_group: [
      20000,
      'Plugin is already Deactive in the group',
    ],
    no_data_to_edit_plugin: [21000, 'No fields found to edit for this plugin'],
    invalid_package_fields: [22000, 'Package details are not valid'],
    plugin_name_too_long: [
      23000,
      'Plugin name cannot be more than 25 characters',
    ],
    plugin_desc_too_long: [
      24000,
      'Plugin name cannot be more than 200 characters',
    ],
    plugin_type_is_invalid: [25000, 'Plugin type is not valid'],
    no_plugin_is_active_in_group: [
      26000,
      'Group does not have any active plugins',
    ],
    cannot_modify_package_if_approved: [
      27000,
      'Sorry, cannot modify packages once the plugin is approved :)',
    ],
    active_plugin_cannot_be_deleted: [
      28000,
      'You need to first deactivate the plugin before deleting it :)',
    ],
    feetransaction_year_mismatch_with_params: [
      29000,
      'Oops, There was some problem, please try again later :)',
    ],
    feetransaction_month_mismatch_with_params: [
      29000,
      'Oops, There was some problem, please try again later :)',
    ],
    fee_amount_invalid: [
      30000,
      'Oops, There was some problem, please try again later :)',
    ],
    no_fee_record_found: [
      31000,
      'No record found for student, please contact the school administrator',
    ],
    group_desc_max_length_exceeds: [
      32000,
      'Group description cannot be more than 250 characters',
    ],
    referral_code_expired: [33000, 'Referral Code Has Expired'],
    referral_code_disabled_on_group: [
      34000,
      'Referral policy is not allowed in this group',
    ],
    amount_input_not_valid: [35000, 'Amount Entered is not valid'],
    description_input_not_valid: [35000, 'Description Entered is not valid'],
    referral_code_does_not_exist: [36000, 'Referral code does not exist'],
    referral_code_not_active_anymore: [
      36000,
      'Referral code is not active anymore',
    ],
    referral_policy_not_active_in_group: [
      37000,
      'Referral policy is not active in this group',
    ],
    referral_code_self_aid: [
      38000,
      'Oops, you cannot use your own referral code',
    ],
    promotional_discount_amount_same: [
      39000,
      'Coupon code not applicable on this amount',
    ],
    referral_discount_amount_same: [
      39000,
      'Referral code not applicable on this amount',
    ],
    group_name_max_length_exceeds: [
      40000,
      'Group name cannot be more than 25 characters',
    ],
    call_of_deleting_userqueue_too_soon: [
      41000,
      'Call of userqueue deletion made too soon',
    ],
    question_upvote_already_done: [
      42000,
      'You have already upvoted this question',
    ],
    answer_upvote_already_done: [43000, 'You have already upvoted this answer'],
    question_already_bookmarked: [
      44000,
      'You have already added this question in your bookmarks',
    ],
    answer_already_bookmarked: [
      44000,
      'You have already added this Answer in your bookmarks',
    ],
    link_not_valid: [45000, 'Link is not valid anymore'],
    question_upvote_not_found: [
      46000,
      'No existing upvote found for this question',
    ],
    answer_upvote_not_found: [47000, 'No existing upvote found for this answer'],
    question_bookmarked_not_found: [
      48000,
      'No existing bookmark found for this question',
    ],
    course_name_invalid: [49000, 'course name is invalid'],
    course_not_activated: [49010, 'course not activated'],
    course_desc_invalid: [49000, 'course description is invalid'],
    course_includes_invalid: [50000, 'Course includes detail is invalid'],
    course_learning_invalid: [51000, 'Course learning detail is invalid'],
    course_seats_invalid: [52000, 'Course seats detail is invalid'],
    course_instructors_invalid: [53000, 'Course instructors detail is invalid'],
    course_packages_empty: [54000, 'Course Packages detail is compulsary'],
    course_packages_invalid: [55000, 'Course Packages detail is invalid'],
    course_instructors_empty: [54000, 'course instructors detail is compulsary'],
    course_only_group_member: [55000, 'You need to be the member of the group'],
    course_only_group_admin: [55000, 'You need to be the admin in the group'],
    free_course_learning_group_invalid: [
      55000,
      'Learning group is invalid for the free course',
    ],
    course_not_found: [56000, 'Course not found'],
    paid_courses_only: [57000, 'Only for paid courses'],
    course_launch_date_invalid: [58000, 'Course launch date is invalid'],
    no_user_groups_as_admin: [
      59000,
      'You are not an admin in any of your groups',
    ],
    course_curriculam_invalid: [60000, 'Course Curriculum is invalid'],
    course_tag_invalid: [61000, 'Course tagline is invalid'],
    no_data_to_edit: [62000, 'Oops, no data to edit the course basic details'],
    feed_plugin_cannot_be_paid: [63000, 'Feed plugin cannot be paid'],
    multiple_feed_cannot_be_created: [
      64000,
      'Multiple feeds cannot be created in a group',
    ],
    invalid_duration_unit: [65000, 'course duration unit is invalid'],
    invalid_duration_base: [65000, 'course duration base is invalid'],
    this_plugin_cannot_be_edited: [66000, 'Sorry, This plugin cannot be edited'],
    aws_upload_fail: [66100, 'Pic upload on aws is unsuccessful'],
    invalid_promo_type: [67000, 'Oops, This promo code is invalid'],
    invalid_promo_module_type: [68000, 'Oops, Promo module is not valid'],
    invalid_promo_type_plugin_id: [
      69000,
      'Oops, promo typ is group plugin specific, but plugin id not supplied',
    ],
    invalid_promo_code: [
      70000,
      'Oops, This promo code is not accoring to eckovation standards',
    ],
    invalid_promo_discount_type: [71000, 'Oops, Promo discount type is invalid'],
    invalid_promo_discount_value: [
      72000,
      'Oops, Promo discount value is invalid',
    ],
    invalid_promo_expiry: [73000, 'Oops, Promo expiry date is invalid'],
    promo_already_exists: [74000, 'Oops, This promo code already exists'],
    promo_not_found: [75000, 'Oops, This promo code does not exists'],
    promo_expiry_cannot_be_beyond_current: [
      76000,
      'Oops, Promo code expiry cannot be changed beyond current datetime',
    ],
    promo_edit_discount_not_data: [
      77000,
      'Oops, NO Edit to edit in promo discount',
    ],
    feed_banned_group_member: [
      66500,
      'Sorry, you are not authorised to perform any this action becuase you have been banned',
    ],
    promo_edit_no_data: [
      78000,
      'Oops, no valid data found to edit promo details',
    ],
    account_not_verified: [79000, 'Oops, account is not verified'],
    not_allowed_to_do_this_activity: [
      80000,
      'Oops, looks like you are not allowed to do this activity',
    ],
    feed_follow_already_done: [81000, 'You are already following this feed'],
    feed_not_following: [82000, 'You are not following this feed anymore'],
    tag_already_following: [83000, 'You are already following this tag'],
    tag_not_following: [84000, 'You are not following this tag anymore'],
    already_used_mobile_referral: [
      85000,
      'You have already used this mobile number as referral',
    ],
    course_not_eligible_for_mobile_referral: [
      86000,
      'Oops, Referral policy is not active for this course, Try another discount code',
    ],
    referral_code_not_found: [
      87000,
      'Oops, This referral code is not valid, Please try another one',
    ],
    code_already_submitted: [
      88000,
      'You have already submitted your code, Resubmission is not allowed',
    ],
    graduation_details_not_complete: [
      89000,
      'Please complete your course graduation details and then reaply for certificate',
    ],
    certificate_not_enabled_for_this_course: [
      89500,
      'This course does not involve certification.',
    ],
    certificate_template_not_of_proper_format: [
      89600,
      "The Certificate Template must have the exact form fields 'Candidate_Name', 'Course_Name', and 'Certificate_Id' mandatorily.",
    ],
    certificate_not_ready_for_this_course: [
      89700,
      'The Certificate for this course is not yet available.',
    ],
    invalid_import_file_type: [89800, 'Please upload a file of type CSV'],
    already_hackathon_registered: [
      90000,
      'You have already registered for this hackathon',
    ],
    hackathon_not_registered: [
      91000,
      'You have not regsitered for this hackathon',
    ],
    hackathon_not_started_yet: [92000, 'Oops, Hackathon has not started yet'],
    hackathon_has_ended: [93000, 'Oops, Hackathon has already finished by now'],
    quiz_share_not_found: [
      94000,
      'Oops, looks like the Quiz link is not active anymore',
    ],
    video_share_not_found: [
      95000,
      'Oops, looks like the Video link is not active anymore',
    ],
    course_share_not_found: [
      96000,
      'Oops, looks like the Course link is not active anymore',
    ],
    ops_notify_panel_group_not_found: [
      97000,
      'Oops, looks like this group is not found',
    ],
    ops_notify_panel_course_not_found: [
      98000,
      'Oops, looks like this course is not found',
    ],
    ops_not_panel_course_not_active: [
      99000,
      'Oops, looks like this course is not active',
    ],
    no_groupplugin_share_found: [
      100000,
      'Oops, looks like this plugin does not exists in this code',
    ],
    campaign_not_found: [101000, 'App Notification Campaign not found'],
    appnotify_campaign_name_too_short: [
      102000,
      'App Notification Campaign name should be atleast 15 chars',
    ],
    appnotify_campaign_text_length_too_short: [
      103000,
      'App Notification Campaign text message length shoudl be atleast 30',
    ],
    appnotify_campaign_img_invalid: [
      104000,
      'App Notification Campaign image is not valid',
    ],
    appnotify_campaign_type_invalid: [
      105000,
      'App Notification Campaign type is not valid',
    ],
    appnotify_campaign_target_audience_invalid: [
      106000,
      'App Notification Campaign selected target audience is invalid',
    ],
    appnotify_campaign_target_platform_invalid: [
      107000,
      'App Notification Campaign selected target paltform is invalid',
    ],
    appnotify_campaign_target_platform_not_allowed: [
      108000,
      'App Notification Campaign selected target platform is not allowed',
    ],
    appnotify_campaign_resource_groupcode_invalid: [
      109000,
      'App Notification Campaign for joingroup, group code to join is invalid',
    ],
    appnotify_campaign_Estimate_Error: [
      110000,
      'App Notification Campaign estimate could not be done',
    ],
    campaign_is_already_completed: [120000, 'Campaign is already Completed'],
    campaign_is_cancelled: [130000, 'Campaign is Cancelled'],
    no_campaigns_found: [140000, 'No Campaigns found'],
    campaign_launch_only_owner: [
      150000,
      'Campaign can be launched only by owner',
    ],
    ongoing_campaign_not_cancel: [160000, 'Ongoing Campaign cannot be Cancelled'],
    campaign_cancel_only_owner: [
      170000,
      'Campaign can be cancelled only by owner',
    ],
    campaign_delete_only_owner: [175000, 'Campaign can be deleted only by owner'],
    only_completed_campaign_be_relaunced: [
      176000,
      'Campaign can be relaunched only after completion',
    ],
    appnotify_campaign_target_audience_not_allowed: [
      180000,
      'App Notification Campaign selected target audience is not Allowed',
    ],
    appnotify_campaign_resource_course_not_found: [
      190000,
      'AppNotification Campaign resource Course not found',
    ],
    appnotify_campaign_resource_external_data_not_found: [
      191000,
      'AppNotification Campaign resource External Data required like Link',
    ],
    appnotify_campaign_resource_course_id_invalid: [
      192000,
      'AppNotification Campaign resource Course Id Invalid',
    ],
    appnotify_campaign_resource_groupcode_not_found: [
      193000,
      'App Notification Campaign for joingroup, group code not found',
    ],
    appnotify_campaign_resource_groupplugin_invalid: [
      194000,
      'AppNotification Campaign resource Group Plugin Id Invalid',
    ],
    appnotify_campaign_resource_groupplugin_not_found: [
      195000,
      'AppNotification Campaign resource Group Plugin Id not found',
    ],
    appnotify_campaign_resource_plugin_not_found: [
      196000,
      'AppNotification Campaign resource Plugin Id not found',
    ],
    appnotify_campaign_resource_quiz_id_invalid: [
      197000,
      'AppNotification Campaign resource Quiz Id is Invalid',
    ],
    appnotify_campaign_resource_quiz_chapter_id_invalid: [
      198000,
      'AppNotification Campaign resource Quiz Chpater Id is Invalid',
    ],
    appnotify_campaign_resource_video_chapter_id_invalid: [
      199000,
      'AppNotification Campaign resource Video Chpater Id is Invalid',
    ],
    appnotify_campaign_resource_lecture_id_invalid: [
      200000,
      'AppNotification Campaign resource Video lecture Id is Invalid',
    ],
    appnotify_campaign_resource_extra_data_required: [
      201000,
      'AppNotification Campaign resource Lecture Extra Data Required',
    ],
    paypal_failed_to_process_authorized_transaction: [
      300000,
      'Failed to process successful PayPal transaction',
    ],
    appnotify_campaign_resource_quiz_chapter_name_missing: [
      202000,
      'AppNotification Campaign resource Quiz Chapter name missing',
    ],
    appnotify_campaign_resource_lecture_chapter_name_missing: [
      203000,
      'AppNotification Campaign resource Video Chapter name missing',
    ],
    appnotify_campaign_resource_course_group_not_found: [
      204000,
      'AppNotification Campaign resource Course Group not found',
    ],
    relaunch_feature_not_allowed: [
      205000,
      'AppNotification Campaign Relaunch feature is currently not allowed',
    ],
    invalid_phone_number: [206000, 'Invalid Phone Number'],
    password_does_not_match: [206500, 'Password does not match'],
    invalid_email: [207000, 'Invalid Email address'],
    email_already_exist: [
      207500,
      'This email ID is already linked to another account',
    ],
    mobile_no_already_exist: [
      207500,
      'This mobile number is already linked to another account',
    ],
    already_confirmed: [207500, 'Your Email ID is already verified!'],
    mobile_already_confirmed: [207500, 'Your mobile number is already verified!'],
    assignment_deadline: [207600, 'Assignment deadline reached'],
    retry_after_30_sec: [208000, 'Please retry after 30 seconds'],
    not_eligible_for_career_portal: [
      888888,
      'You are not eligible for career portal',
    ],
    invalid_facebook_url: [400, 'Invalid Facebook url please enter a valid url'],
    invalid_linkedin_url: [400, 'Invalid LinkedIn url please enter a valid url'],
    invalid_date: [400, 'Invalid date'],
    date_can_not_in_past: [400, "Date can't be in past"],
    word_count_exceeds: [701000, 'Assignment submitted too large.'],
    invalid_file_format: [702000, 'Please upload a text file.'],
    word_limit_no_match: [703000, 'Assignment submitted too short.'],
    Grade_Value_Invalid_Format: [703500, 'Grade value is in invalid format'],
    invalid_timezone: [704000, 'Invalid Timezone'],
    invalid_date: [705000, 'Invalid Date'],
    duration_exceeded: [706000, 'Duration range should be between 1 to 7 days'],
    no_file_detected: [707000, 'Please add a file to upload'],
    ppt_file_size_excedeed: [708000, 'Max file Size should be 4 mb'],
    invalid_ppt_file_type: [709000, 'File type should be ppt/pptx/odp'],
    no_user_questions_found: [710000, 'No user attempted questions found'],
    invalid_user: [
      720000,
      'Please enter a valid host email address. Please contact the administrator in case of doubt',
    ],
    invalid_time: [
      731000,
      'The end date and time of the lecture must be after the lecture start date and time',
    ],
    invalid_characters: [
      740000,
      'The title or description entered by you is too long',
    ],
    ep_not_verified: [
      751000,
      'Please verify your email address by accessing your Imarticus Web Portal',
    ],
    impartus_disabled: [752000, 'There are no class recordings for this course'],
    impartus_login_fail: [
      741000,
      'Please contact the admin to activate your Class Recordings',
    ],
    leadsquare_invalid_phone_number: [206000, 'Invalid Phone Number'],
    leadsquare_generic_error: [
      206000,
      'We are unable to process your request. Please try again later',
    ],
    leadsquare_invalid_parameters: [
      206000,
      'Please enter your details correctly, as we are not able to process your request',
    ],
    leadsquare_invalid_phone_number: [
      206000,
      'The mobile number you have provided is invalid. Please enter a valid mobile number',
    ],
    leadsquare_invalid_email: [
      206000,
      'The email address you have provided is invalid. Please enter a valid email address',
    ],
    leadsquare_invalid_preferred_program: [206000, 'Please select a program'],
  }
  
  module.exports = errors
  